global using OneOf;
global using OneOf.Types;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Definit.Validation;
global using Definit.Primitives;
global using Microsoft.FeatureManagement;
global using Definit.Utils;
global using Definit.Validation.FluentValidation;